[package]
name = "leet-code"
version = "0.1.0"
authors = ["Донатио Г. Николашин <nikolashin.d@icloud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]